- hosts: grafana
  become: yes
  tasks:
    - name: Install necessary packages
      apt:
        name:
          - apt-transport-https
          - software-properties-common
          - wget
        state: present

    - name: Add Grafana GPG key
      ansible.builtin.shell: |
        wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg > /dev/null

    - name: Add Grafana repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/grafana.list
        line: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
        create: yes

    - name: Update repositories and install Grafana
      apt:
        update_cache: yes
        name: grafana
        state: present

    - name: Start and enable Grafana
      systemd:
        name: grafana-server
        state: started
        enabled: yes
