- hosts: prometheus
  become: yes
  tasks:
    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v2.30.0/prometheus-2.30.0.linux-amd64.tar.gz"
        dest: "/tmp/prometheus.tar.gz"

    - name: Extract Prometheus tarball
      unarchive:
        src: "/tmp/prometheus.tar.gz"
        dest: "/usr/local/bin"
        remote_src: yes
        extra_opts: ['--strip-components=1']

    - name: Create Prometheus user
      user:
        name: prometheus
        shell: /sbin/nologin
        createhome: no

    - name: Create directories for Prometheus
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
      loop:
        - "/etc/prometheus"
        - "/var/lib/prometheus"

    - name: Create Prometheus configuration file
      copy:
        content: |
          global:
            scrape_interval: 15s
          rule_files:
            - "alert_rules.yml"
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']
            - job_name: 'node'
              static_configs:
                - targets: ['{{ node_exporter_ip }}:9100']
          alerting:
            alertmanagers:
            - static_configs:
              - targets:
                - 'localhost:9093'
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus

    - name: Copy Alert Rules File
      copy:
        src: "/mnt/c/Users/chris/OneDrive/Desktop/Techstarter Kurs/Ü133 - Prometheus - Alerting/alert_rules.yml"
        dest: "/etc/prometheus/alert_rules.yml"
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: Create Prometheus systemd service file
      copy:
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus/ \
            --web.console.templates=/usr/local/bin/consoles \
            --web.console.libraries=/usr/local/bin/console_libraries

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/prometheus.service

    - name: Reload systemd to apply new service
      systemd:
        daemon_reload: yes

    - name: Start and enable Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes
